services:
  - type: web
    name: offline-reports-telegram-system
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
